Pin black to higher version to solve click complaints
kedro-org/kedro-starters pull request #77
Opened 2022-03-29 12:54 UTC by MerelTheisenQB

Signed-off-by: Merel Theisen <merel.theisen@quantumblack.com>

## Motivation and Context
The latest click 8.1.0 is incompatible with black versions < 22.3.0

https://github.com/pallets/click/issues/2232
https://github.com/psf/black/issues/2964

## Checklist

- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Assigned myself to the PR
- [ ] Added tests to cover my changes

2022-03-29 13:26 UTC, lorenabalan approved these changes

2022-03-29 13:26 UTC, lorenabalan commented on astro-airflow-iris/{{ cookiecutter.repo_name }}/src/requirements.txt
> +black>=22.3.0
```suggestion
black>=22.3.0, <23.0
```

2022-03-29 13:26 UTC, lorenabalan commented on pandas-iris/{{ cookiecutter.repo_name }}/src/requirements.txt
> +black>=22.3.0
```suggestion
black>=22.3.0, <23.0
```

2022-03-29 13:26 UTC, lorenabalan commented on pyspark-iris/{{ cookiecutter.repo_name }}/src/requirements.txt
> +black>=22.3.0
```suggestion
black>=22.3.0, <23.0
```

2022-03-29 13:26 UTC, lorenabalan commented on pyspark/{{ cookiecutter.repo_name }}/src/requirements.txt
> +black>=22.3.0
```suggestion
black>=22.3.0, <23.0
```

2022-03-29 13:26 UTC, lorenabalan commented on test_requirements.txt
> +black>=22.3.0
```suggestion
black>=22.3.0, <23.0
```

2022-03-29 13:55 UTC, noklam requested changes

2022-03-29 13:55 UTC, noklam commented on test_requirements.txt
>  click<8.0
`click<9.0` to match with kedro develop branch

2022-03-30 16:36 UTC, lorenabalan approved these changes
🏆

2022-03-30 16:45 UTC, lorenabalan commented on test_requirements.txt
> +black~=22.0
We can also remove L2 and the python version thing on L1.

2022-03-30 16:51 UTC, noklam approved these changes
I see the CI is failing for `kedro-telemetry`, do we also have py39 py310 support for the plugins or it will comes after `0.18` release?

2022-03-30 17:22 UTC, MerelTheisenQB commented
> I see the CI is failing for `kedro-telemetry`, do we also have py39 py310 support for the plugins or it will comes after `0.18` release?

We'll need to add that support for all plugins after kedro `0.18.0` is released.

2022-03-30 19:32 UTC, merged